Proyecto2_201403775/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^usac_networking/', include('usac_networking.urls', namespace="usac_networking")),
    url(r'^admin/', include(admin.site.urls)),
]

usac_networking/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView, name='index'),
    url(r'^login/', views.login, name='login'),
    url(r'^Admin/', views.AdminView, name='Admin_index'),
    url(r'^user/', views.UserView, name='User_index'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^search/', views.logout, name='search'),
    url(r'^sign_in/', views.sign_in, name='sign_in'),
    url(r'^pvalidate/', views.pvalidate, name='pvalidate'),
    url(r'^validate/(?P<val_id>([a-z]|[A-Z]|[0-9]){50})/', views.validate, name='validate'),
    url(r'^forgot/', views.forgotpass, name='forgot'),
    url(r'^facultades/$', views.FacultadIndex, name='facultad'),
    url(r'^facultades/nueva/', views.FacultadNueva, name='fac_nueva'),
    url(r'^facultades/update/(?P<f_id>[0-9]+)/', views.FacultadMod, name='fac_update'),
    url(r'^carreras/$', views.CarreraIndex, name='carrera'),
    url(r'^carreras/nueva/', views.CarreraNueva, name='car_nueva'),
    url(r'^carreras/update/(?P<c_id>[0-9]+)/', views.CarreraMod, name='car_update'),
    url(r'^ciencias/$', views.CienciaIndex, name='ciencia'),
    url(r'^ciencias/nueva/', views.CienciaNueva, name='cie_nueva'),
    url(r'^ciencias/update/(?P<c_id>[0-9]+)/', views.CienciaMod, name='cie_update'),
    url(r'^cargo/$', views.CargoIndex, name='cargo'),
    url(r'^cargo/nuevo/', views.CargoNueva, name='carg_nueva'),
    url(r'^cargo/update/(?P<c_id>[0-9]+)/', views.CargoMod, name='carg_update'),
    url(r'^usuarios/$', views.UsuarioIndex, name='usuario'),
    url(r'^usuarios/nuevo/', views.UsuarioNueva, name='usu_nueva'),
    url(r'^usuarios/update/(?P<u_id>[0-9]+)/', views.UsuarioMod, name='usu_update'),
    url(r'^usuarios/detalle/(?P<u_id>[0-9]+)/', views.UsuarioDetail, name='user_detail'),
    url(r'^profile/', views.Usuarioprofile, name='profile'),
    url(r'^circulos/$', views.CirculoIndex, name='circulos'),
    url(r'^circulos/Admin/$', views.CirculoAdminIndex, name='circulos_admin'),
    url(r'^circulos/nuevo/', views.CirculoNew, name='circulo_nuevo'),
    url(r'^circulos/add/(?P<c_id>[0-9]+)/', views.CirculoAdd, name='circulo_add'),
    url(r'^circulos/actualizar/(?P<c_id>[0-9]+)/', views.CirculoUpdate, name='circulo_update'),
    url(r'^circulos/info/(?P<c_id>[0-9]+)/', views.Circuloinfo, name='circulo_info'),
    url(r'^circulos/notificacion/', views.CirculoNo, name='notificacion_circulo'),
    url(r'^temas/$', views.TemaIndex, name='tema'),
    url(r'^temas/Admin/$', views.TemaAdminIndex, name='tema_admin'),
    url(r'^tema/nuevo/', views.TemaNew, name='tema_nuevo'),
    url(r'^tema/add/(?P<t_id>[0-9]+)/', views.TemaAdd, name='tema_add'),
    url(r'^tema/add/ciencia/(?P<t_id>[0-9]+)/', views.TemaAddCiencia, name='tema_add_ciencia'),
    url(r'^tema/add/facultad/(?P<t_id>[0-9]+)/', views.TemaAddFacultad, name='tema_add_facultad'),
    url(r'^tema/add/carrera/(?P<t_id>[0-9]+)/', views.TemaAddCarrera, name='tema_add_carrera'),
    url(r'^tema/add/usuario/(?P<t_id>[0-9]+)/', views.TemaAddUsuario, name='tema_add_usuario'),
    url(r'^tema/actualizar/(?P<t_id>[0-9]+)/', views.TemaUpdate, name='tema_update'),
    url(r'^tema/info/(?P<t_id>[0-9]+)/', views.TemaInfo, name='tema_info'),
    url(r'^tema/notificacion/', views.TemaNo, name='notificacion_tema'),
    url(r'^Comentario/$', views.Comment, name='comment'),
    url(r'^Comentarios/$', views.getComments, name='comments'),
    url(r'^Comentario/del/$', views.CommentDel, name='comment_del'),
    url(r'^amistades/$', views.Amistades, name='amistades'),
    url(r'^ws/users/$', views.WSUsuarios, name='wsusers'),
    url(r'^ws/user/$', views.WSUsuario, name='wsuser'),
    url(r'^ws/facultades/$', views.WSFacultades, name='wsfacultades'),
    url(r'^ws/search/$', views.WSBusqueda, name='wsbusqueda'),
    url(r'^ws/login/$', views.WSLogin),
    url(r'^ws/temas/$', views.WSTemas),
    url(r'^chat/$', views.Chat, name='chat'),
    url(r'^asignacion/$', views.AsignacionIndex , name='asig'),
    url(r'^asignacion/cargo/', views.AsignacionCargo, name='asig_cargo'),
    url(r'^asignacion/asig/', views.AsignacionAsignacion, name='asig_asig'),
    url(r'^asignacion/ciencia/', views.AsignacionCiencia, name='asig_ciencia'),
]

usac_networking/views/Asignacion.py
# -*- coding: utf-8 -*-
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.forms import modelformset_factory
from django.http import Http404
from django import forms

from usac_networking.models import Ciencia_Asignado, Cargo_Usuario, Usuario, Asignacion

def AsignacionIndex(request):
    if request.session.get('log_in'):
        title = 'Usac NetWorking - Asignaciones'

        cargo_relformset = modelformset_factory(Cargo_Usuario, fields=('cargo','Usuario'),max_num=1)
        asignacion_relformset = modelformset_factory(Asignacion, fields=('carrera','usuario'),max_num=1)
        ciencia_relformset = modelformset_factory(Ciencia_Asignado, fields=('usuario','ciencia'),max_num=1)

        cargo_relform = cargo_relformset(queryset=Cargo_Usuario.objects.none(),initial=[{'Usuario':request.session['user_id'],}])
        asignacion_relform = asignacion_relformset(queryset=Asignacion.objects.none(),initial=[{'usuario':request.session['user_id'],}])
        ciencia_relform = ciencia_relformset(queryset=Ciencia_Asignado.objects.none(),initial=[{'usuario':request.session['user_id'],}])

        cargos = Cargo_Usuario.objects.filter(Usuario=request.session['user_id'])
        asignaciones = Asignacion.objects.filter(usuario=request.session['user_id'])
        ciencias = Ciencia_Asignado.objects.filter(usuario=request.session['user_id'])

        return render(request, 'usac_networking/User/Asignacion/related.html',{
                    'title'         : title,
                    'session'       : request.session['session'],
                    'cargoform'     : cargo_relform,
                    'asigform'      : asignacion_relform,
                    'cienciaform'   : ciencia_relform,
                    'cargos'        : cargos,
                    'asignaciones'  : asignaciones,
                    'ciencias'      : ciencias,
                    })
    return HttpResponseRedirect(reverse('usac_networking:index'))

def AsignacionCargo(request):
    if request.session.get('log_in'):
        title = 'Usac NetWorking - Asignaciones'
        err_msg = ''
        msg = ''

        cargo_relformset = modelformset_factory(Cargo_Usuario, fields=('cargo','Usuario'),max_num=1)
        asignacion_relformset = modelformset_factory(Asignacion, fields=('carrera','usuario'),max_num=1)
        ciencia_relformset = modelformset_factory(Ciencia_Asignado, fields=('usuario','ciencia'),max_num=1)

        if request.method == "POST":
            cargo_relform = cargo_relformset(request.POST,request.FILES)
            if cargo_relform.is_valid():
                cargo_relform.save()
                msg = 'Se ha añadido el cargo con exito'
            else:
                err_msg = cargo_relform.errors
        else:
            cargo_relform = cargo_relformset(queryset=Cargo_Usuario.objects.none(),initial=[{'Usuario':request.session['user_id'],}])

        asignacion_relform = asignacion_relformset(queryset=Asignacion.objects.none(),initial=[{'usuario':request.session['user_id'],}])
        ciencia_relform = ciencia_relformset(queryset=Ciencia_Asignado.objects.none(),initial=[{'usuario':request.session['user_id'],}])

        cargos = Cargo_Usuario.objects.filter(Usuario=request.session['user_id'])
        asignaciones = Asignacion.objects.filter(usuario=request.session['user_id'])
        ciencias = Ciencia_Asignado.objects.filter(usuario=request.session['user_id'])

        return render(request, 'usac_networking/User/Asignacion/related.html',{
                    'title'         : title,
                    'session'       : request.session['session'],
                    'cargoform'     : cargo_relform,
                    'asigform'      : asignacion_relform,
                    'cienciaform'   : ciencia_relform,
                    'cargos'        : cargos,
                    'asignaciones'  : asignaciones,
                    'ciencias'      : ciencias,
                    'msg'           : msg,
                    'err_msg'       : err_msg,
                    })
    return HttpResponseRedirect(reverse('usac_networking:index'))

def AsignacionAsignacion(request):
    if request.session.get('log_in'):
        title = 'Usac NetWorking - Asignaciones'
        err_msg = ''
        msg = ''

        cargo_relformset = modelformset_factory(Cargo_Usuario, fields=('cargo','Usuario'),max_num=1)
        asignacion_relformset = modelformset_factory(Asignacion, fields=('carrera','usuario'),max_num=1)
        ciencia_relformset = modelformset_factory(Ciencia_Asignado, fields=('usuario','ciencia'),max_num=1)

        if request.method == "POST":
            asignacion_relform = asignacion_relformset(request.POST,request.FILES)
            if asignacion_relform.is_valid():
                asignacion_relform.save()
                msg = 'Asignacion realizada con exito'
            else:
                err_msg = asignacion_relform.errors
        else:
            asignacion_relform = asignacion_relformset(queryset=Asignacion.objects.none(),initial=[{'usuario':request.session['user_id'],}])

        cargo_relform = cargo_relformset(queryset=Cargo_Usuario.objects.none(),initial=[{'Usuario':request.session['user_id'],}])
        ciencia_relform = ciencia_relformset(queryset=Ciencia_Asignado.objects.none(),initial=[{'usuario':request.session['user_id'],}])

        cargos = Cargo_Usuario.objects.filter(Usuario=request.session['user_id'])
        asignaciones = Asignacion.objects.filter(usuario=request.session['user_id'])
        ciencias = Ciencia_Asignado.objects.filter(usuario=request.session['user_id'])

        return render(request, 'usac_networking/User/Asignacion/related.html',{
                    'title'         : title,
                    'session'       : request.session['session'],
                    'cargoform'     : cargo_relform,
                    'asigform'      : asignacion_relform,
                    'cienciaform'   : ciencia_relform,
                    'cargos'        : cargos,
                    'asignaciones'  : asignaciones,
                    'ciencias'      : ciencias,
                    'msg'           : msg,
                    'err_msg'       : err_msg,
                    })
    return HttpResponseRedirect(reverse('usac_networking:index'))

def AsignacionCiencia(request):
    if request.session.get('log_in'):
        title = 'Usac NetWorking - Asignaciones'
        err_msg = ''
        msg = ''

        cargo_relformset = modelformset_factory(Cargo_Usuario, fields=('cargo','Usuario'),max_num=1)
        asignacion_relformset = modelformset_factory(Asignacion, fields=('carrera','usuario'),max_num=1)
        ciencia_relformset = modelformset_factory(Ciencia_Asignado, fields=('usuario','ciencia'),max_num=1)

        if request.method == "POST":
            ciencia_relform = ciencia_relformset(request.POST,request.FILES)
            if ciencia_relform.is_valid():
                ciencia_relform.save()
                msg = 'Ciencia Agregada con exito'
            else:
                err_msg = ciencia_relform.errors
        else:
            ciencia_relform = ciencia_relformset(queryset=Ciencia_Asignado.objects.none(),initial=[{'usuario':request.session['user_id'],}])

        cargo_relform = cargo_relformset(queryset=Cargo_Usuario.objects.none(),initial=[{'Usuario':request.session['user_id'],}])
        asignacion_relform = asignacion_relformset(queryset=Asignacion.objects.none(),initial=[{'usuario':request.session['user_id'],}])

        cargos = Cargo_Usuario.objects.filter(Usuario=request.session['user_id'])
        asignaciones = Asignacion.objects.filter(usuario=request.session['user_id'])
        ciencias = Ciencia_Asignado.objects.filter(usuario=request.session['user_id'])

        return render(request, 'usac_networking/User/Asignacion/related.html',{
                    'title'         : title,
                    'session'       : request.session['session'],
                    'cargoform'     : cargo_relform,
                    'asigform'      : asignacion_relform,
                    'cienciaform'   : ciencia_relform,
                    'cargos'        : cargos,
                    'asignaciones'  : asignaciones,
                    'ciencias'      : ciencias,
                    'msg'           : msg,
                    'err_msg'       : err_msg,
                    })
    return HttpResponseRedirect(reverse('usac_networking:index'))

usac_networking/views/Chat.py
# -*- coding: utf-8 -*-
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.forms import modelformset_factory
from django.http import Http404
from django import forms

from usac_networking.models import Tema, Ciencia_rel, Facultad_rel, Carrera_rel, Usuario_inv, Respuesta

def Chat(request):
    if request.session.get('log_in'):
        if request.session['log_in'] == 2:
            title = 'Usac NetWorking - Chat'
            return render(request, 'usac_networking/User/Chat/list.html',{
                        'title'         : title,
                        'session'       : request.session['session'],
                        })
    return HttpResponseRedirect(reverse('usac_networking:index'))

usac_networking/views/Index.py
# -*- coding: utf-8 -*-
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.forms import modelformset_factory
from django.http import Http404

from usac_networking.models import Usuario, Tema, Circulo, Facultad, Ciencia, Carrera

def IndexView(request):
    title = 'Usac NetWorking - index'
    if request.session.get('log_in'):
        if request.session['log_in'] == 1:
            return HttpResponseRedirect(reverse('usac_networking:Admin_index'))
        if request.session['log_in'] == 2:
            return HttpResponseRedirect(reverse('usac_networking:User_index'))
    request.session['session'] = 0
    temas = Tema.objects.all().reverse()[:5]
    return render(request, 'usac_networking/Frontend/home.html',{
                'title':title,
                'session'   : 0,
                'temas'     :temas
                })

def AdminView(request):
    title = 'Admin - Usac NetWorking'
    if request.session.get('log_in'):
        if request.session['log_in'] == 1:
            usuarios = Usuario.objects.all().reverse()[:5]
            temas = Tema.objects.all().reverse()[:5]
            return render(request, 'usac_networking/Admin/home.html',{
                        'title':title,
                        'session'   : request.session['session'],
                        'temas'     : temas,
                        'usuarios'  : usuarios,
                        })
    return HttpResponseRedirect(reverse('usac_networking:index'))

def UserView(request):
    title = 'User - Usac NetWorking'
    if request.session.get('log_in'):
        if request.session['log_in'] == 2:
            temas = Tema.objects.filter(usuario__pk=request.session['user_id']).reverse()
            return render(request, 'usac_networking/User/home.html',{
                        'title'     : title,
                        'session'   : request.session['session'],
                        'temas'          : temas,
                        })
    return HttpResponseRedirect(reverse('usac_networking:index'))

usac_networking/templates/usac_networking/User/Circulo/info.html
{% load static %}
<!DOCTYPE html>
<html>
  {% include 'usac_networking/public/header.html' %}
  <body>
    {% include 'usac_networking/public/navigation.html' %}
    <div class="container">
      {% if msg %}
        <div class="alert alert-info">{{ msg }}</div>
      {% endif %}
      <div class="panel panel-default">
        <div class="panel-heading">
          <div class="row">
            <div class="col-sm-12">
              <h2>
                {{ circulo.nombre }}
                {% if editable %}
                  <a href="{% url 'usac_networking:circulo_update' circulo.pk %}" type="button" class="btn btn-default btn-xs">
                    <span class="glyphicon glyphicon-pencil"></span> Modificar
                  </a>
                {% endif %}
              </h2>
            </div>
          </div>
        </div>
        <div class="panel-body">
          <div class="panel-group">
            <div class="panel panel-primary">
              <div class="panel-heading">
                Informacion
              </div>
              <div class="panel-body">
                  <div class="table-responsive">
                    <table class="table table-striped">
                      <tbody>
                        <tr>
                          <th>Propietario</th>
                          <td>{{ circulo.usuario.nombre }} [ {{ circulo.usuario.carnet }} ]</td>
                        </tr>
                        <tr>
                          <th>Descripcion</th>
                          <td>{{ circulo.descripcion }}</td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
              </div>
            </div>
            <hr>
            <div class="panel panel-info">
              <div class="panel-heading">
                Integrantes
              </div>
              <div class="panel-body">
                <div class="table-responsive">
                  <table class="table table-striped">
                    <thead>
                      <th>Nombre</th>
                      <th>carnet</th>
                      <th>Catedratico</th>
                      <th>Estado</th>
                      {% if editable %}
                        <th>&nbsp;</th>
                      {% endif %}
                    </thead>
                    <tbody>
                      {% for usuario in circulo_des %}
                        <tr>
                          <td>
                            <a href="{% url 'usac_networking:user_detail' usuario.usuario.pk %}">
                              {{ usuario.usuario.nombre }} {{ usuario.usuario.apellido }}
                            </a>
                          </td>
                          <td>{{ usuario.usuario.carnet }}</td>
                          <td>
                            {% if usuario.usuario.catedratico == True %}
                              Catedratico
                            {% else %}
                              Estudiante
                            {% endif %}
                          </td>
                          {% if usuario.estado == 0  %}
                            <td>Pendiente</td>
                          {% else  %}
                            <td>Participando</td>
                          {% endif %}
                          {% if editable %}
                            <td>
                              <div class="btn-group pull-right">
                                <button data-id="{{ usuario.usuario.pk }}" type="button" class="btn btn-default btn-xs udel"><span class="glyphicon glyphicon-remove"></span></button>
                              </div>
                            </td>
                          {% endif %}
                        </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="alert_win" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-sm">
        <div class="modal-content">
          <form id="del_confirm" method="post" data="{% url 'usac_networking:circulo_info' circulo.pk %}">
            {% csrf_token %}
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
              <h4 class="modal-title" id="myModalLabel">Confirmar</h4>
            </div>
            <div class="modal-body">
              <p>Esta Seguro que Desea remover este usuario de este grupo?</p>
              <input type="hidden" name="f_op" value="del"/>
              <input type="hidden" id="f_id" name="f_id" value=""/>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
              <button type="submit" class="btn btn-danger">Si</button>
            </div>
          </form>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    {% include 'usac_networking/public/footer.html' %}
    <script src="{% static 'usac_networking/js/del_list.js' %}"></script>
  </body>
</html>

usac_networking/templates/usac_networking/User/Circulo/list.html
{% load static %}
<!DOCTYPE html>
<html>
  {% include 'usac_networking/public/header.html' %}
  <body>
    {% include 'usac_networking/public/navigation.html' %}
    <div class="container">
      {% if msg %}
        <div class="alert alert-info">{{ msg }}</div>
      {% endif %}
      {% if err_msg %}
        <div class="alert alert-danger">{{ err_msg }}</div>
      {% endif %}
      <div class="panel-group">
        {% if notificaciones|length > 0 %}
        <div class="panel panel-info">
          <div class="panel-heading">
            Solicitudes de pertenecencia
          </div>
          <div class="panel-body">
            {% for notificacion in notificaciones %}
              <div id="notificacion{{ notificacion.pk }}" class="row">
                <div class="col-sm-9">
                  <div class="text-justify">
                    El usuario: {{ notificacion.circulo.usuario.nombre }} te ha mandado una solicitud de pertenecencia para el grupo creado por el llamado "<a href="{% url 'usac_networking:circulo_info' notificacion.circulo.pk %}">{{ notificacion.circulo.nombre }}</a>"
                  </div>
                </div>
                <div class="col-sm-3">
                  <div class="btn-group pull-right">
                    <a data-url="{% url 'usac_networking:notificacion_circulo' %}" data-op="aceptar" data-id="{{ notificacion.pk }}" href="#" type="button" class="btn btn-default btn-xs notificacion"><span class="glyphicon glyphicon-ok-sign"></span> Aceptar</a>
                    <a data-url="{% url 'usac_networking:notificacion_circulo' %}" data-op="rechazar" data-id="{{ notificacion.pk }}" href="#" type="button" class="btn btn-default btn-xs notificacion"><span class="glyphicon glyphicon-remove-sign"></span> Rechazar</a>
                  </div>
                </div>
              </div>
              <div id="notificacion_a{{ notificacion.pk }}" class="row msg_notificacion">
                <div class="col-sm-12">
                  <div class="alert alert-info">
                    Ahora perteneces al grupo "{{ notificacion.circulo.nombre }}"
                  </div>
                </div>
              </div>
              <div id="notificacion_b{{ notificacion.pk }}" class="row msg_notificacion">
                <div class="col-sm-12">
                  <div class="alert alert-info">
                    Haz rechazado la solicitud de pertenecencia para el grupo "{{ notificacion.circulo.nombre }}"
                  </div>
                </div>
              </div>
              <hr>
            {% endfor %}
          </div>
        </div>
        {% endif %}
        <div class="panel panel-primary">
          <div class="panel-heading">
            <span class="glyphicon glyphicon-king"></span> Circulos Sociales
            <div class="pull-right">
              <a href="{% url 'usac_networking:circulo_nuevo' %}" type="button" class="btn btn-default btn-xs">
              <span class="glyphicon glyphicon-plus"></span>
              </a>
            </div>
          </div>
          <div class="panel-body">
            <div class="panel-group">
              <div class="panel panel-default">
                <div class="panel-heading">
                  <div class="text-center">
                    Mis grupos
                  </div>
                </div>
                <div class="panel-body">
                  <div class="table-responsive">
                    <table class="table table-striped">
                      <thead>
                        <th>Cod.</th>
                        <th>Nombre.</th>
                        <th>Ciencia</th>
                        <th>Descripcion</th>
                        <th>&nbsp;</th>
                      </thead>
                      <tbody>
                        {% if circulos|length > 0 %}
                          {% for circulo in circulos %}
                            <tr>
                              <td>{{ circulo.pk }}</td>
                              <td>{{ circulo.nombre }}</td>
                              <td>{{ circulo.ciencia }}</td>
                              <td>{{ circulo.descripcion }}</td>
                              <td>
                                <div class="btn-group pull-right">
                                  <a href="{% url 'usac_networking:circulo_info' circulo.pk %}" type="button" class="btn btn-default btn-xs"><span class="glyphicon glyphicon-info-sign"></span></a>
                                  <a href="{% url 'usac_networking:circulo_update' circulo.pk %}" type="button" class="btn btn-default btn-xs"><span class="glyphicon glyphicon-pencil"></span></a>
                                  <a href="{% url 'usac_networking:circulo_add' circulo.pk %}" type="button" class="btn btn-default btn-xs"><span class="glyphicon glyphicon-plus"></span></a>
                                  <button data-id="{{ circulo.pk }}" type="button" class="btn btn-default btn-xs udel"><span class="glyphicon glyphicon-remove"></span></button>
                                </div>
                              </td>
                            </tr>
                          {% endfor %}
                        {% else %}
                          <tr>
                            <th colspan="5">
                              <div class="text-center">
                                Actualmente no tienes ningun grupo
                              </div>
                            </th>
                          </tr>
                        {% endif %}
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
              <div class="panel panel-default">
                <div class="panel-heading">
                  <div class="text-center">
                    Circulos a donde pertenesco
                  </div>
                </div>
                <div class="panel-body">
                  <div class="table-responsive">
                    <table class="table table-striped">
                      <thead>
                        <th>Cod.</th>
                        <th>Propetario</th>
                        <th>Nombre.</th>
                        <th>Ciencia</th>
                        <th>Descripcion</th>
                        <th>&nbsp;</th>
                      </thead>
                      <tbody>
                        {% if circulosinv|length > 0 %}
                          {% for circulo_inv in circulosinv %}
                            <tr id="circulo{{ circulo_inv.pk }}">
                              <td>{{ circulo_inv.circulo.pk }}</td>
                              <td>{{ circulo_inv.circulo.usuario }}</td>
                              <td>{{ circulo_inv.circulo.nombre }}</td>
                              <td>{{ circulo_inv.circulo.ciencia }}</td>
                              <td>{{ circulo_inv.circulo.descripcion }}</td>
                              <td>
                                <div class="btn-group pull-right">
                                  <a data-url="{% url 'usac_networking:notificacion_circulo' %}" data-op="salir" data-id="{{ circulo_inv.pk }}" href="#" type="button" class="btn btn-default btn-xs notificacion"><span class="glyphicon glyphicon-log-out"></span> Salir</a>
                                </div>
                              </td>
                            </tr>
                          {% endfor %}
                        {% else %}
                          <tr>
                            <th colspan="5">
                              <div class="text-center">
                                Actualmente no perteneces a ningun grupo
                              </div>
                            </th>
                          </tr>
                        {% endif %}
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="alert_win" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    	<div class="modal-dialog modal-sm">
    		<div class="modal-content">
    			<form id="del_confirm" method="post" data="{% url 'usac_networking:circulos' %}">
            {% csrf_token %}
            <div class="modal-header">
    					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    					<h4 class="modal-title" id="myModalLabel">Confirmar</h4>
    				</div>
    				<div class="modal-body">
    					<p>Esta Seguro que Desea Eliminar esta Facultad?</p>
              <input type="hidden" name="f_op" value="del"/>
              <input type="hidden" id="f_id" name="f_id" value=""/>
    				</div>
    				<div class="modal-footer">
    					<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
    					<button type="submit" class="btn btn-danger">Si</button>
    				</div>
    			</form>
    		</div><!-- /.modal-content -->
    	</div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    {% include 'usac_networking/public/footer.html' %}
    <script src="{% static 'usac_networking/js/notificaciones.js' %}"></script>
  </body>
</html>