Proyecto2_201403775/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^usac_networking/', include('usac_networking.urls', namespace="usac_networking")),
    url(r'^admin/', include(admin.site.urls)),
]

usac_networking/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView, name='index'),
    url(r'^login/', views.login, name='login'),
    url(r'^Admin/', views.AdminView, name='Admin_index'),
    url(r'^user/', views.UserView, name='User_index'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^search/', views.logout, name='search'),
    url(r'^sign_in/', views.sign_in, name='sign_in'),
    url(r'^pvalidate/', views.pvalidate, name='pvalidate'),
    url(r'^validate/(?P<val_id>([a-z]|[A-Z]|[0-9]){50})/', views.validate, name='validate'),
    url(r'^forgot/', views.forgotpass, name='forgot'),
    url(r'^facultades/$', views.FacultadIndex, name='facultad'),
    url(r'^facultades/nueva/', views.FacultadNueva, name='fac_nueva'),
    url(r'^facultades/update/(?P<f_id>[0-9]+)/', views.FacultadMod, name='fac_update'),
    url(r'^carreras/$', views.CarreraIndex, name='carrera'),
    url(r'^carreras/nueva/', views.CarreraNueva, name='car_nueva'),
    url(r'^carreras/update/(?P<c_id>[0-9]+)/', views.CarreraMod, name='car_update'),
    url(r'^ciencias/$', views.CienciaIndex, name='ciencia'),
    url(r'^ciencias/nueva/', views.CienciaNueva, name='cie_nueva'),
    url(r'^ciencias/update/(?P<c_id>[0-9]+)/', views.CienciaMod, name='cie_update'),
    url(r'^cargo/$', views.CargoIndex, name='cargo'),
    url(r'^cargo/nuevo/', views.CargoNueva, name='carg_nueva'),
    url(r'^cargo/update/(?P<c_id>[0-9]+)/', views.CargoMod, name='carg_update'),
    url(r'^usuarios/$', views.UsuarioIndex, name='usuario'),
    url(r'^usuarios/nuevo/', views.UsuarioNueva, name='usu_nueva'),
    url(r'^usuarios/update/(?P<u_id>[0-9]+)/', views.UsuarioMod, name='usu_update'),
    url(r'^usuarios/detalle/(?P<u_id>[0-9]+)/', views.UsuarioDetail, name='user_detail'),
    url(r'^profile/', views.Usuarioprofile, name='profile'),
    url(r'^circulos/$', views.CirculoIndex, name='circulos'),
    url(r'^circulos/Admin/$', views.CirculoAdminIndex, name='circulos_admin'),
    url(r'^circulos/nuevo/', views.CirculoNew, name='circulo_nuevo'),
    url(r'^circulos/add/(?P<c_id>[0-9]+)/', views.CirculoAdd, name='circulo_add'),
    url(r'^circulos/actualizar/(?P<c_id>[0-9]+)/', views.CirculoUpdate, name='circulo_update'),
    url(r'^circulos/info/(?P<c_id>[0-9]+)/', views.Circuloinfo, name='circulo_info'),
    url(r'^circulos/notificacion/', views.CirculoNo, name='notificacion_circulo'),
    url(r'^temas/$', views.TemaIndex, name='tema'),
    url(r'^temas/Admin/$', views.TemaAdminIndex, name='tema_admin'),
    url(r'^tema/nuevo/', views.TemaNew, name='tema_nuevo'),
    url(r'^tema/add/(?P<t_id>[0-9]+)/', views.TemaAdd, name='tema_add'),
    url(r'^tema/add/ciencia/(?P<t_id>[0-9]+)/', views.TemaAddCiencia, name='tema_add_ciencia'),
    url(r'^tema/add/facultad/(?P<t_id>[0-9]+)/', views.TemaAddFacultad, name='tema_add_facultad'),
    url(r'^tema/add/carrera/(?P<t_id>[0-9]+)/', views.TemaAddCarrera, name='tema_add_carrera'),
    url(r'^tema/add/usuario/(?P<t_id>[0-9]+)/', views.TemaAddUsuario, name='tema_add_usuario'),
    url(r'^tema/actualizar/(?P<t_id>[0-9]+)/', views.TemaUpdate, name='tema_update'),
    url(r'^tema/info/(?P<t_id>[0-9]+)/', views.TemaInfo, name='tema_info'),
    url(r'^tema/notificacion/', views.TemaNo, name='notificacion_tema'),
    url(r'^Comentario/$', views.Comment, name='comment'),
    url(r'^Comentarios/$', views.getComments, name='comments'),
    url(r'^Comentario/del/$', views.CommentDel, name='comment_del'),
    url(r'^amistades/$', views.Amistades, name='amistades'),
    url(r'^ws/users/$', views.WSUsuarios, name='wsusers'),
    url(r'^ws/user/$', views.WSUsuario, name='wsuser'),
    url(r'^ws/facultades/$', views.WSFacultades, name='wsfacultades'),
    url(r'^ws/search/$', views.WSBusqueda, name='wsbusqueda'),
    url(r'^ws/login/$', views.WSLogin),
    url(r'^ws/temas/$', views.WSTemas),
    url(r'^chat/$', views.Chat, name='chat'),
    url(r'^asignacion/$', views.AsignacionIndex , name='asig'),
    url(r'^asignacion/cargo/', views.AsignacionCargo, name='asig_cargo'),
    url(r'^asignacion/asig/', views.AsignacionAsignacion, name='asig_asig'),
    url(r'^asignacion/ciencia/', views.AsignacionCiencia, name='asig_ciencia'),
]

usac_networking/views/Asignacion.py
# -*- coding: utf-8 -*-
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.forms import modelformset_factory
from django.http import Http404
from django import forms

from usac_networking.models import Ciencia_Asignado, Cargo_Usuario, Usuario, Asignacion

def AsignacionIndex(request):
    if request.session.get('log_in'):
        title = 'Usac NetWorking - Asignaciones'

        cargo_relformset = modelformset_factory(Cargo_Usuario, fields=('cargo','Usuario'),max_num=1)
        asignacion_relformset = modelformset_factory(Asignacion, fields=('carrera','usuario'),max_num=1)
        ciencia_relformset = modelformset_factory(Ciencia_Asignado, fields=('usuario','ciencia'),max_num=1)

        cargo_relform = cargo_relformset(queryset=Cargo_Usuario.objects.none(),initial=[{'Usuario':request.session['user_id'],}])
        asignacion_relform = asignacion_relformset(queryset=Asignacion.objects.none(),initial=[{'usuario':request.session['user_id'],}])
        ciencia_relform = ciencia_relformset(queryset=Ciencia_Asignado.objects.none(),initial=[{'usuario':request.session['user_id'],}])

        cargos = Cargo_Usuario.objects.filter(Usuario=request.session['user_id'])
        asignaciones = Asignacion.objects.filter(usuario=request.session['user_id'])
        ciencias = Ciencia_Asignado.objects.filter(usuario=request.session['user_id'])

        return render(request, 'usac_networking/User/Asignacion/related.html',{
                    'title'         : title,
                    'session'       : request.session['session'],
                    'cargoform'     : cargo_relform,
                    'asigform'      : asignacion_relform,
                    'cienciaform'   : ciencia_relform,
                    'cargos'        : cargos,
                    'asignaciones'  : asignaciones,
                    'ciencias'      : ciencias,
                    })
    return HttpResponseRedirect(reverse('usac_networking:index'))

def AsignacionCargo(request):
    if request.session.get('log_in'):
        title = 'Usac NetWorking - Asignaciones'
        err_msg = ''
        msg = ''

        cargo_relformset = modelformset_factory(Cargo_Usuario, fields=('cargo','Usuario'),max_num=1)
        asignacion_relformset = modelformset_factory(Asignacion, fields=('carrera','usuario'),max_num=1)
        ciencia_relformset = modelformset_factory(Ciencia_Asignado, fields=('usuario','ciencia'),max_num=1)

        if request.method == "POST":
            cargo_relform = cargo_relformset(request.POST,request.FILES)
            if cargo_relform.is_valid():
                cargo_relform.save()
                msg = 'Se ha añadido el cargo con exito'
            else:
                err_msg = cargo_relform.errors
        else:
            cargo_relform = cargo_relformset(queryset=Cargo_Usuario.objects.none(),initial=[{'Usuario':request.session['user_id'],}])

        asignacion_relform = asignacion_relformset(queryset=Asignacion.objects.none(),initial=[{'usuario':request.session['user_id'],}])
        ciencia_relform = ciencia_relformset(queryset=Ciencia_Asignado.objects.none(),initial=[{'usuario':request.session['user_id'],}])

        cargos = Cargo_Usuario.objects.filter(Usuario=request.session['user_id'])
        asignaciones = Asignacion.objects.filter(usuario=request.session['user_id'])
        ciencias = Ciencia_Asignado.objects.filter(usuario=request.session['user_id'])

        return render(request, 'usac_networking/User/Asignacion/related.html',{
                    'title'         : title,
                    'session'       : request.session['session'],
                    'cargoform'     : cargo_relform,
                    'asigform'      : asignacion_relform,
                    'cienciaform'   : ciencia_relform,
                    'cargos'        : cargos,
                    'asignaciones'  : asignaciones,
                    'ciencias'      : ciencias,
                    'msg'           : msg,
                    'err_msg'       : err_msg,
                    })
    return HttpResponseRedirect(reverse('usac_networking:index'))

def AsignacionAsignacion(request):
    if request.session.get('log_in'):
        title = 'Usac NetWorking - Asignaciones'
        err_msg = ''
        msg = ''

        cargo_relformset = modelformset_factory(Cargo_Usuario, fields=('cargo','Usuario'),max_num=1)
        asignacion_relformset = modelformset_factory(Asignacion, fields=('carrera','usuario'),max_num=1)
        ciencia_relformset = modelformset_factory(Ciencia_Asignado, fields=('usuario','ciencia'),max_num=1)

        if request.method == "POST":
            asignacion_relform = asignacion_relformset(request.POST,request.FILES)
            if asignacion_relform.is_valid():
                asignacion_relform.save()
                msg = 'Asignacion realizada con exito'
            else:
                err_msg = asignacion_relform.errors
        else:
            asignacion_relform = asignacion_relformset(queryset=Asignacion.objects.none(),initial=[{'usuario':request.session['user_id'],}])

        cargo_relform = cargo_relformset(queryset=Cargo_Usuario.objects.none(),initial=[{'Usuario':request.session['user_id'],}])
        ciencia_relform = ciencia_relformset(queryset=Ciencia_Asignado.objects.none(),initial=[{'usuario':request.session['user_id'],}])

        cargos = Cargo_Usuario.objects.filter(Usuario=request.session['user_id'])
        asignaciones = Asignacion.objects.filter(usuario=request.session['user_id'])
        ciencias = Ciencia_Asignado.objects.filter(usuario=request.session['user_id'])

        return render(request, 'usac_networking/User/Asignacion/related.html',{
                    'title'         : title,
                    'session'       : request.session['session'],
                    'cargoform'     : cargo_relform,
                    'asigform'      : asignacion_relform,
                    'cienciaform'   : ciencia_relform,
                    'cargos'        : cargos,
                    'asignaciones'  : asignaciones,
                    'ciencias'      : ciencias,
                    'msg'           : msg,
                    'err_msg'       : err_msg,
                    })
    return HttpResponseRedirect(reverse('usac_networking:index'))

def AsignacionCiencia(request):
    if request.session.get('log_in'):
        title = 'Usac NetWorking - Asignaciones'
        err_msg = ''
        msg = ''

        cargo_relformset = modelformset_factory(Cargo_Usuario, fields=('cargo','Usuario'),max_num=1)
        asignacion_relformset = modelformset_factory(Asignacion, fields=('carrera','usuario'),max_num=1)
        ciencia_relformset = modelformset_factory(Ciencia_Asignado, fields=('usuario','ciencia'),max_num=1)

        if request.method == "POST":
            ciencia_relform = ciencia_relformset(request.POST,request.FILES)
            if ciencia_relform.is_valid():
                ciencia_relform.save()
                msg = 'Ciencia Agregada con exito'
            else:
                err_msg = ciencia_relform.errors
        else:
            ciencia_relform = ciencia_relformset(queryset=Ciencia_Asignado.objects.none(),initial=[{'usuario':request.session['user_id'],}])

        cargo_relform = cargo_relformset(queryset=Cargo_Usuario.objects.none(),initial=[{'Usuario':request.session['user_id'],}])
        asignacion_relform = asignacion_relformset(queryset=Asignacion.objects.none(),initial=[{'usuario':request.session['user_id'],}])

        cargos = Cargo_Usuario.objects.filter(Usuario=request.session['user_id'])
        asignaciones = Asignacion.objects.filter(usuario=request.session['user_id'])
        ciencias = Ciencia_Asignado.objects.filter(usuario=request.session['user_id'])

        return render(request, 'usac_networking/User/Asignacion/related.html',{
                    'title'         : title,
                    'session'       : request.session['session'],
                    'cargoform'     : cargo_relform,
                    'asigform'      : asignacion_relform,
                    'cienciaform'   : ciencia_relform,
                    'cargos'        : cargos,
                    'asignaciones'  : asignaciones,
                    'ciencias'      : ciencias,
                    'msg'           : msg,
                    'err_msg'       : err_msg,
                    })
    return HttpResponseRedirect(reverse('usac_networking:index'))

usac_networking/views/Chat.py
# -*- coding: utf-8 -*-
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.forms import modelformset_factory
from django.http import Http404
from django import forms

from usac_networking.models import Tema, Ciencia_rel, Facultad_rel, Carrera_rel, Usuario_inv, Respuesta

def Chat(request):
    if request.session.get('log_in'):
        if request.session['log_in'] == 2:
            title = 'Usac NetWorking - Chat'
            return render(request, 'usac_networking/User/Chat/list.html',{
                        'title'         : title,
                        'session'       : request.session['session'],
                        })
    return HttpResponseRedirect(reverse('usac_networking:index'))

usac_networking/views/Index.py
# -*- coding: utf-8 -*-
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.forms import modelformset_factory
from django.http import Http404

from usac_networking.models import Usuario, Tema, Circulo, Facultad, Ciencia, Carrera

def IndexView(request):
    title = 'Usac NetWorking - index'
    if request.session.get('log_in'):
        if request.session['log_in'] == 1:
            return HttpResponseRedirect(reverse('usac_networking:Admin_index'))
        if request.session['log_in'] == 2:
            return HttpResponseRedirect(reverse('usac_networking:User_index'))
    request.session['session'] = 0
    temas = Tema.objects.all().reverse()[:5]
    return render(request, 'usac_networking/Frontend/home.html',{
                'title':title,
                'session'   : 0,
                'temas'     :temas
                })

def AdminView(request):
    title = 'Admin - Usac NetWorking'
    if request.session.get('log_in'):
        if request.session['log_in'] == 1:
            usuarios = Usuario.objects.all().reverse()[:5]
            temas = Tema.objects.all().reverse()[:5]
            return render(request, 'usac_networking/Admin/home.html',{
                        'title':title,
                        'session'   : request.session['session'],
                        'temas'     : temas,
                        'usuarios'  : usuarios,
                        })
    return HttpResponseRedirect(reverse('usac_networking:index'))

def UserView(request):
    title = 'User - Usac NetWorking'
    if request.session.get('log_in'):
        if request.session['log_in'] == 2:
            temas = Tema.objects.filter(usuario__pk=request.session['user_id']).reverse()
            return render(request, 'usac_networking/User/home.html',{
                        'title'     : title,
                        'session'   : request.session['session'],
                        'temas'          : temas,
                        })
    return HttpResponseRedirect(reverse('usac_networking:index'))

usac_networking/templates/usac_networking/Frontend/forgot.html
<!DOCTYPE html>
<html>
  {% load static %}
  {% include 'usac_networking/public/header.html' %}
  <link rel="stylesheet" type="text/css" href="{% static 'usac_networking/css/Actual/forms_login.css' %}" />
  <body>
    {% include 'usac_networking/public/navigation.html' %}
    <div class="container">
      {% if correo %}
        <h1>Hemos Enviado un correo a {{ correo }}******* con la credenciales de esta cuenta</h1>
      {% else %}
        {% if err_msg %}
          <div class="alert alert-danger">{{ err_msg }}</div>
        {% endif %}
        <form class="form-signin" action="{% url 'usac_networking:forgot' %}" method="post" >
          <h2 class="form-signin-heading">Olvidadizo!...</h2>
          {% csrf_token %}
          <input type="number" class="form-control" name="user_carne" placeholder="Carnet Universitario" required autofocus>
          <input type="submit" value="Enviar" class="btn btn-lg btn-primary btn-block">
        </form>
      {% endif %}
      <center><a href="{% url 'usac_networking:login' %}">iniciar sesion</a></center>
    </div>
    {% include 'usac_networking/public/footer.html' %}
  </body>
</html>

usac_networking/templates/usac_networking/Frontend/home.html
{% load static %}
<!DOCTYPE html>
<html>
  {% include 'usac_networking/public/header.html' %}
  <body>
    {% include 'usac_networking/public/navigation.html' %}
    <div class="container">
      <div class="contenido">
        <div class="row">
          <div class="col-md-12">
            <h2>Ultimos Temas Publicados</h2>
          </div>
        </div>
        {% for tema in temas %}
          <div class="row">
            <div class="col-xs-12">
              <div class="panel panel-default">
                <div class="panel-heading">
                  <h3>{{ tema.titulo }} ({{ tema.fecha }})</h3>
                </div>
                <div class="panel-body">
                  <img class="img-responsive" src="{% static "usac_networking/images/user_profile_images/" %}{{ tema.imagen }}" alt="Card image cap">
                  <br>
                  {% autoescape off %}
                    <div class="card-text text-justify">
                      {{ tema.contenido|linebreaks|capfirst|truncatechars:100 }}
                    </div>
                  {% endautoescape %}
                </div>
                <div class="panel-footer">
                  Posteado por: <a href="{% url 'usac_networking:user_detail' tema.usuario.pk %}">{{ tema.usuario.nombre }}</a>
                  <div class="pull-right">
                    <a href="{% url 'usac_networking:tema_info' tema.pk %}" type="button" class="btn btn-default btn-xs"><span class="glyphicon glyphicon-plus"></span> Seguir Leyendo</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <hr>
        {% endfor %}
      </div>
    </div>
    {% include 'usac_networking/public/footer.html' %}
  </body>
</html>

usac_networking/templates/usac_networking/Frontend/login.html
<!DOCTYPE html>
<html>
  {% load static %}
  {% include 'usac_networking/public/header.html' %}
  <body>
    {% include 'usac_networking/public/navigation.html' %}
    <div class="container">
      {% if err_msg %}
        <div class="alert alert-danger">{{ err_msg }}</div>
      {% endif %}
      <form class="form_login" class="form-signin" action="{% url 'usac_networking:login' %}" method="post" >
        {% csrf_token %}
        <div class="panel panel-default">
          <div class="panel-heading">
            <h2 class="form-signin-heading">Log in</h2>
          </div>
          <div class="panel-body">
            <div class="input-group">
              <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
              <input type="number" name="user_carne" placeholder="Carnet Universitario" required autofocus>
            </div>
            <div class="input-group">
              <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
              <input type="password" name="password" placeholder="Contraseña" required>
            </div>
          </div>
          <div class="panel-footer">
            <button type="submit" class="btn btn-lg btn-primary btn-block">Ingresar</button>
          </div>
        </div>
      </form>
      <center><a href="{% url 'usac_networking:forgot' %}">olvide mi contraseña...</a></center>
    </div>
    {% include 'usac_networking/public/footer.html' %}
  </body>
</html>

usac_networking/templates/usac_networking/Frontend/pvalidate.html
<!DOCTYPE html>
<html>
  {% load static %}
  {% include 'usac_networking/public/header.html' %}
  <link rel="stylesheet" type="text/css" href="{% static 'usac_networking/css/Actual/forms_signup.css' %}" />
  <body>
    {% include 'usac_networking/public/navigation.html' %}
    <div class="container">
      <h1> hemos enviado un correo de validacion a tu correo. porfavor sigue las instrucciones que se te plantean ahi </h1>
    </div>
    {% include 'usac_networking/public/footer.html' %}
  </body>
</html>

usac_networking/templates/usac_networking/Frontend/sign_up.html
<!DOCTYPE html>
<html>
  {% load static %}
  {% include 'usac_networking/public/header.html' %}
  <body>
    {% include 'usac_networking/public/navigation.html' %}
    <div class="container">
      {% if err_msg %}
        <div class="alert alert-danger">{{ err_msg }}</div>
      {% endif %}
      <form class="form_registro" action="{% url 'usac_networking:sign_in' %}" method="post" enctype="multipart/form-data" >
        {% csrf_token %}
        <div class="panel panel-default">
          <div class="panel-heading">
            <h2 class="form-signin-heading">Registrate</h2>
          </div>
          <div class="panel-body">
            {{ formset.management_form }}
              {% for form in formset %}
                {% for field in form %}
                    <div class="form-group">
                      {% if field.label != 'Id' %}
                        {{ field.label_tag }}
                      {% endif %}
                      {{ field }}
                    </div>
                {% endfor %}
              {% endfor %}
          </div>
          <div class="panel-footer">
            <button type="submit" class="btn btn-lg btn-primary btn-block">Registrar</button>
          </div>
        </div>
      </form>
    </div>
    {% include 'usac_networking/public/footer.html' %}
  </body>
</html>

usac_networking/templates/usac_networking/Frontend/validate.html
<!DOCTYPE html>
<html>
  {% load static %}
  {% include 'usac_networking/public/header.html' %}
  <link rel="stylesheet" type="text/css" href="{% static 'usac_networking/css/Actual/forms_signup.css' %}" />
  <body>
    {% include 'usac_networking/public/navigation.html' %}
    <div class="container">
      {% if resultado == 1 %}
        <h1>tu cuenta ha sido confirmada. ya puedes utilizarla con tranquilidad</h1>
      {% endif %}
      {% if resultado == 2 %}
        <h1>ha expirado este link de confirmacion. porfavor contacta al administrador de la pagina</h1>
      {% endif %}
      {% if resultado == 3 %}
        <h1>este usuario ya ha sido confirmado.</h1>
      {% endif %}
      {% if resultado == -1 %}
        <h1>Esta cuenta ha sido suspendida, contacta con uno de los administradores de la paguina</h1>
      {% endif %}
      {% if resultado == -2 %}
        <h1>Esta cuenta ha sido eliminada, contacta con uno de los administradores de la paguina</h1>
      {% endif %}
    </div>
    {% include 'usac_networking/public/footer.html' %}
  </body>
</html>